from __future__ import annotations

from datetime import datetime
from enum import StrEnum
from typing import Any, Literal

from pydantic import BaseModel, Field


class Trust(StrEnum):
    """Where text came from. Drives guard policy and memory eligibility."""

    USER = "user"      # console + voice: hard-blocked on guard hit, may write memory
    SENSOR = "sensor"  # attacker-influenceable: wrapped on guard hit, never writes memory
    SYSTEM = "system"  # generated by us


SEVERITY_INFO = 0
SEVERITY_LOW = 1
SEVERITY_MEDIUM = 2
SEVERITY_HIGH = 3
SEVERITY_CRITICAL = 4


class ThreatLevel(StrEnum):
    BENIGN = "benign"
    LOW = "low"
    ELEVATED = "elevated"
    HIGH = "high"
    CRITICAL = "critical"
    UNKNOWN = "unknown"


# --- Widgets ---------------------------------------------------------------

WidgetType = Literal[
    "stat", "gauge", "timeseries", "bar", "donut", "table",
    "kv", "log", "status", "image", "gallery", "video", "audio", "map", "toggle",
    # A button that runs one of the plugin's own commands. Its data_source says
    # what the button is called and which command it invokes, so the dashboard
    # still ships no plugin-specific code -- see `action` in widgets.jsx.
    "action",
]


class WidgetSpec(BaseModel):
    """How a plugin wants a slice of its data rendered. Declarative only."""

    type: WidgetType
    title: str = ""
    props: dict[str, Any] = Field(default_factory=dict)
    data_source: str | None = None
    span: int = 6  # bootstrap columns out of 12


class StreamDescriptor(BaseModel):
    kind: Literal["hls", "mjpeg", "webrtc", "clip"]
    url: str
    name: str = ""


class AlarmRuleSpec(BaseModel):
    key: str
    name: str
    description: str = ""
    sensor_id: str | None = None
    spec: dict[str, Any] = Field(default_factory=dict)
    default_armed: bool = False


class ToolSpec(BaseModel):
    name: str
    description: str
    parameters: dict[str, Any] = Field(default_factory=dict)


class SensorDescriptor(BaseModel):
    id: str
    name: str
    kind: str = "generic"
    widgets: list[WidgetSpec] = Field(default_factory=list)
    streams: list[StreamDescriptor] = Field(default_factory=list)
    alarm_rules: list[AlarmRuleSpec] = Field(default_factory=list)
    tools: list[ToolSpec] = Field(default_factory=list)


# --- Events ----------------------------------------------------------------

class MediaRef(BaseModel):
    path: str
    mime: str
    sha256: str | None = None
    bytes: int | None = None
    duration_ms: int | None = None


class Event(BaseModel):
    sensor_id: str
    plugin: str = ""
    ts: datetime | None = None
    severity: int = SEVERITY_INFO
    kind: str = "generic"
    summary: str = ""
    sensor_text: str | None = None
    payload: dict[str, Any] = Field(default_factory=dict)
    media: list[MediaRef] = Field(default_factory=list)


class Classification(BaseModel):
    threat_level: ThreatLevel = ThreatLevel.UNKNOWN
    classification: str = ""
    reasoning: str = ""
    suggested_action: str = ""
